
 INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Arbas','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Sahagún','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Astorga','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Tuy','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Dueñas','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Zamora','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Toro','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Cuéllar','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Ledesma','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Salamanca','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','León','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Navasfrías','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Santibañez','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Portezuelo','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Magacela','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Trujillo','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Zalamea','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Plasencia','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Ponferrada','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Cistierna','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Sanabria','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','El Bierzo','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Fabero','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Bembibre','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Benavente','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Saldaña','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Valdehuesa','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Roa','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Villablino','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Villalpando','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Medina de Rioseco','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Villabrágima','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Tordesillas','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Villa Lalle','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Mucientes','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Taracueña','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Sacramenia','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Rueda','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Alba','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Baños','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Alhándiga','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Béjar','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Montemayor','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Amusco','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Fromista','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Palencia','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Sepúlveda','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Ardón','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Simancas','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Banuncias','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Escalada','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Melgar','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Valdesalce','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Aldeaseca','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Valmuza','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Támara','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Carrión','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Paredes de Nava','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Quintanilla','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Perales','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','San Cebrián','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Ruiforco','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','San Félis','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Babia','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Laciana','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Los Ancares','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Coyanza','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Turienzo','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Felechas','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Oliegos','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Omaña','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Murias','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Yuso','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Suso','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Torrebarrio','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Cubiechas','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Truébano','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','Villasecino','REINO DE LEÓN');
INSERT INTO `region_ciudades` (`REGIONID`,`NOMBRE`,`TEMPORAL`) VALUES ('59','La Majúa','REINO DE LEÓN');
 

