
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (66,1,17,6,12,22);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (66,2,18,3,12,22);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (66,3,23,10,12,15);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (66,4,25,11,4,7);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (66,5,30,12,2,6);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (66,6,36,19,4,9);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (66,7,36,22,5,9);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (66,8,37,23,2,9);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (66,9,32,20,12,19);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (66,10,30,14,12,20);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (66,11,26,12,12,22);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (66,12,20,8,12,22);
 
 
 

