
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (65,1,8,1,12,21);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (65,2,10,2,12,21);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (65,3,13,3,12,15);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (65,4,17,6,0,7);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (65,5,21,10,0,6);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (65,6,25,14,0,5);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (65,7,28,16,0,9);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (65,8,27,16,0,9);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (65,9,24,14,12,19);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (65,10,19,6,12,20);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (65,11,14,6,12,21);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (65,12,10,2,12,21);
 
 
 

