
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (60,1,11,5,12,21);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (60,2,12,3,12,21);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (60,3,12,5,12,17);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (60,4,16,4,12,17);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (60,5,19,7,0,12);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (60,6,27,9,4,20);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (60,7,27,11,1,11);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (60,8,28,15,2,20);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (60,9,23,10,2,10);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (60,10,19,8,0,10);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (60,11,12,10,0,10);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (60,12,10,6,12,21);
 
 
 

