
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (64,1,6,-4,12,22);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (64,2,8,-2,12,22);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (64,3,13,0,12,15);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (64,4,17,4,0,7);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (64,5,21,9,0,6);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (64,6,25,15,0,9);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (64,7,28,16,0,9);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (64,8,27,15,0,9);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (64,9,24,11,12,19);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (64,10,18,6,12,20);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (64,11,1,2,12,22);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (64,12,7,-4,12,22);
 
 
 

