
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (61,1,9,2,12,21);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (61,2,10,3,12,21);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (61,3,14,4,12,16);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (61,4,16,6,12,15);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (61,5,19,13,0,6);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (61,6,22,12,1,4);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (61,7,24,10,1,8);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (61,8,24,12,2,8);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (61,9,23,10,2,10);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (61,10,17,5,12,19);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (61,11,9,2,12,21);
INSERT INTO `region_clima` (`REGIONID`,`MES`,`TEMP_MAX`, `TEMP_MIN`, `TIEMPO_MIN`,`TIEMPO_MAX`) VALUES (61,12,10,6,12,21);
 
 
 

