
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,1,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (1,67,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,2,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (2,67,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,3,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (3,67,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,4,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (4,67,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,5,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (5,67,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,6,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (6,67,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,7,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (7,67,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,8,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (8,67,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,9,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (9,67,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,10,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (10,67,72,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,11,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (11,67,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,12,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (12,67,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,13,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (13,67,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,14,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (14,67,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,15,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (15,67,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,16,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (16,67,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,17,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (17,67,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,18,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (18,67,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,19,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (19,67,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,20,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (20,67,60,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,21,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (21,67,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,22,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (22,67,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,23,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (23,67,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,24,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (24,67,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,25,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (25,67,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,26,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (26,67,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,27,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (27,67,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,28,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (28,67,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,29,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (29,67,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,30,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (30,67,96,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,31,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (31,67,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,32,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (32,67,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,33,120,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (33,67,120,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,34,132,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (34,67,132,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,35,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (35,67,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,36,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (36,67,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,37,132,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (37,67,132,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,38,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (38,67,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,39,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (39,67,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,40,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (40,67,60,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,41,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (41,67,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,42,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (42,67,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,43,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (43,67,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,44,24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (44,67,24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,45,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (45,67,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,46,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (46,67,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,47,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (47,67,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,48,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (48,67,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,49,24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (49,67,24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,50,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (50,67,36,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,51,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (51,67,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,52,120,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (52,67,120,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (53,67,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,53,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (54,67,240,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,54,240,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,55,228,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (55,67,228,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,56,228,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (56,67,228,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,57,228,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (57,67,228,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,58,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,67,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,59,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,67,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,60,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,67,96,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,61,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (61,67,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,62,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (62,67,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,63,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (63,67,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,64,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,67,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,65,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (65,67,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,66,216,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (66,67,216,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,67,12,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,67,12,0,0);
 

