
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (1,59, 18,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (2,59, 18,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (3,59, 30,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (4,59, 42,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (5,59, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (6,59, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (7,59, 42,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (8,59, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (9,59, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (10,59, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (11,59, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (12,59, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (13,59, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (14,59, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (15,59, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (16,59, 98,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (17,59, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (18,59, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (19,59, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (20,59, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (21,59, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (22,59, 96,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (23,59, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (24,59, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (25,59, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (26,59,114,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (27,59, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (28,59, 102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (29,59, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (30,59, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (31,59, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (32,59, 102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (33,59, 102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (34,59, 114,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (35,59, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (36,59, 102,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (37,59, 116,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (38,59, 116,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (39,59, 116,0,0);
 
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (40,59, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (41,59, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (42,59,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (43,59,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (44,59, 96,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (45,59, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (46,59,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (47,59, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (48,59, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (49,59, 108,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (50,59, 102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (51,59, 108,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (52,59, 18,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (53,59,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (54,59,198,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (55,59,186,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (56,59,186,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (57,59,186,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,59,18,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,59,12,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,1, 18,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,2, 18,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,3, 30,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 4,42,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,5, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,6, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,7, 42,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 8, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 9, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,10, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,11, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 12, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,13, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 14, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,15, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 16, 98,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 17, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 18, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 19,66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,20, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,21, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,22, 96,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,23,  78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 24, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 25, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,26,114,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 27,90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,28, 102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,29, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 30,90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 31, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,32, 102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,33, 102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 34,114,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 35, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,36, 102,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 37, 116,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 38, 116,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,39, 116,0,0);
 
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 40,66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,41, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 42, 84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,43, 84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 44,96,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 45,78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,46, 84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 47,90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 48,90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,49, 108,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 50, 102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 51, 108,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59, 52, 18,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,53, 72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,54, 198,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,55, 186,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,56,186,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,57, 186,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,59,18,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,59,12,0,0);