
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,1,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (1,64,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,2,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (2,64,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,3,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (3,64,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,4,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (4,64,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,5,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (5,64,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,6,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (6,64,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,7,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (7,64,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,8,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (8,64,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,9,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (9,64,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,10,24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (10,64,24,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,11,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (11,64,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,12,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (12,64,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,13,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (13,64,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,14,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (14,64,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,15,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (15,64,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,16,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (16,64,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,17,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (17,64,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,18,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (18,64,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,19,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (19,64,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,20,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (20,64,60,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,21,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (21,64,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,22,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (22,64,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,23,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (23,64,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,24,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (24,64,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,25,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (25,64,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,26,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (26,64,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,27,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (27,64,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,28,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (28,64,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,29,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (29,64,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,30,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (30,64,36,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,31,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (31,64,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,32,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (32,64,36,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,33,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (33,64,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,34,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (34,64,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,35,24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (35,64,24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,36,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (36,64,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,37,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (37,64,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,38,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (38,64,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,39,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (39,64,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,40,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (40,64,48,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,41,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (41,64,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,42,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (42,64,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,43,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (43,64,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,44,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (44,64,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,45,24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (45,64,24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,46,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (46,64,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,47,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (47,64,58,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,48,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (48,64,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,49,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (49,64,96,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,50,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (50,64,84,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,51,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (51,64,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,52,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (52,64,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (53,64,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,53,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (54,64,168,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,54,168,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,55,156,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (55,64,156,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,56,156,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (56,64,156,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,57,156,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (57,64,156,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,58,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,64,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,59,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,64,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,60,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,64,60,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,61,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (61,64,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,62,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (62,64,84,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,63,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (63,64,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,64,12,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,64,12,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,65,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (65,64,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,66,144,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (66,64,144,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (64,67,108,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (67,64,108,0,0);
 

