
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (1,58, 24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (2,58, 18,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (3,58, 18,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (4,58, 30,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (5,58, 42,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (6,58, 42,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (7,58, 30,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (8,58, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (9,58, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (10,58, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (11,58, 42,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (12,58, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (13,58, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (14,58, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (15,58, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (16,58, 90,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (17,58, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (18,58, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (19,58, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (20,58, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (21,58, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (22,58, 84,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (23,58, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (24,58, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (25,58, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (26,58,102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (27,58, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (28,58, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (29,58, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (30,58, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (31,58, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (32,58, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (33,58, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (34,58, 102,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (35,58, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (36,58, 90,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (37,58, 102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (38,58, 102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (39,58, 102,0,0);
 
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (40,58, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (41,58, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (42,58,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (43,58,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (44,58, 84,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (45,58, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (46,58,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (47,58, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (48,58, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (49,58, 96,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (50,58, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (51,58, 96,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (52,58, 18,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (53,58,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (54,58,186,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (55,58,172,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (56,58,172,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (57,58,172,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,58,12,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,1, 24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,2, 18,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,3, 18,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 4,30,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,5, 42,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,6, 42,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,7, 30,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 8, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 9,54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,10, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,11, 42,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 12,54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,13, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 14,54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,15, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 16, 90,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 17, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 18, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 19,54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,20, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,21, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,22, 84,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,23,  66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 24, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 25, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,26,102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 27,78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,28, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,29, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 30,78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 31, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,32, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,33, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 34,102,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 35, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,36, 90,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 37, 102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 38,102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,39, 102,0,0);
 
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 40,54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,41, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 42, 72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,43, 72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 44,84,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 45,66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,46, 72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 47,78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 48,78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,49, 96,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 50, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 51, 96,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58, 52, 18,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,53, 60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,54, 186,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,55, 172,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,56,172,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,57, 172,0,0);
 
 
 
 
 
 
 
 
 
 
 
 
 

