
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (1,60, 24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (2,60, 24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (3,60, 24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (4,60, 24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (5,60, 24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (6,60, 30,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (7,60,30,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (8,60, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (9,60, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (10,60, 48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (11,60, 42,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (12,60, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (13,60, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (14,60, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (15,60, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (16,60, 90,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (17,60, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (18,60, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (19,60, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (20,60, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (21,60, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (22,60, 84,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (23,60, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (24,60, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (25,60, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (26,60,102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (27,60, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (28,60, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (29,60, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (30,60, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (31,60, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (32,60, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (33,60, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (34,60, 90,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (35,60, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (36,60, 78,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (37,60, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (38,60, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (39,60, 90,0,0);
 
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (40,60, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (41,60, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (42,60,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (43,60,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (44,60, 84,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (45,60, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (46,60,72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (47,60, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (48,60, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (49,60, 96,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (50,60, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (51,60, 96,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (52,60, 36,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (53,60,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (54,60,172,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (55,60,162,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (56,60,162,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (57,60,162,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,60,24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,60,18,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,60,12,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,1, 24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,2, 24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,3, 24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 4, 24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,5, 24,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,6, 30,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,7, 30,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 8, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 9, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,10,48,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,11, 42,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 12, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,13, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 14, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,15, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 16, 90,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 17, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 18, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 19, 54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,20, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,21, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,22, 84,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,23,  66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 24, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 25, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,26,102,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 27,78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,28, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,29, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 30, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 31, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,32, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,33, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 34,90,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 35, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,36, 78,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 37, 90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 38, 78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,39, 90,0,0);
 
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 40,54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,41, 66,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 42, 72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,43, 72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 44,84,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 45,54,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,46, 72,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 47,78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 48,78,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,49, 96,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 50,90,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 51, 96,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60, 52, 36,0,0);
 
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,53,60,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,54, 172,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,55, 162,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,56,162,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,57, 162,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (58,60,24,0,0);
 
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (59,60,18,0,0);
INSERT INTO `region_distancia` (`REGIONID_ORIGEN`,`REGIONID_DESTINO`,`DISTANCIA_CAMPO`, `DISTANCIA_MONTANYAS`, `DISTANCIA_MAR`) VALUES (60,60,12,0,0);
 
 
 
 
 
 
 
 
 
 
 
 
 

