 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1232, 1,1232,'Recesvundo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1233, 1,1233,'Frunimius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1234, 1,1234,'Teodomiro',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1235, 1,1235,'Fortes',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1236, 1,1236,'Obecco',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1237, 1,1237,'Piniolo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1238, 1,1238,'Sancho',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1239, 1,1239,'Sanzo',0);



INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1240, 1,1240,'Vicente',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1241, 1,1241,'Hermenegildo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1242, 1,1242,'Fredenando',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1243, 1,1243,'Fernando',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1244, 1,1244,'Diego',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1245, 1,1245,'Diácono',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1246, 1,1246,'Donino',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1247, 1,1247,'García',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1248, 1,1248,'Venancio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1249, 1,1249,'Alfoneta',0);


INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1250, 1,1250,'Juan',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1251, 1,1251,'Sisebuto',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1252, 1,1252,'Vermudo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1253, 1,1253,'Braulio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1254, 1,1254,'Cisila',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1255, 1,1255,'Dulcidio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1256, 1,1256,'Félix',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1257, 1,1257,'Froilán',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1258, 1,1258,'Gundesalvo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1259, 1,1259,'Gudesteo',0);


INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1260, 1,1260,'Julián',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1261, 1,1261,'Taion',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1262, 1,1262,'Teodolfo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1263, 1,1263,'Teodulfo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1264, 1,1264,'Amphilocius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1265, 1,1265,'Christoforo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1266, 1,1266,'Ferro',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1267, 1,1267,'Cipriano',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1268, 1,1268,'Flazino',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1269, 1,1269,'Gudemundo',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1270, 1,1270,'Justo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1271, 1,1271,'Lecino',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1272, 1,1272,'Magino',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1273, 1,1273,'Mauro',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1274, 1,1274,'Maxitus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1275, 1,1275,'Menicius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1276, 1,1276,'Orbanus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1277, 1,1277,'Pepino',0);
 INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1278, 1,1278,'Recamundo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1279, 1,1279,'Recesviro',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1280, 1,1280,'Sesinando',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1281, 1,1281,'Stephano',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1282, 1,1282,'Teodislu',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1283, 1,1283,'Abderraman',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1284, 1,1284,'Abdias',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1285, 1,1285,'Abzuleman',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1286, 1,1286,'Adica',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1287, 1,1287,'Alvaro',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1288, 1,1288,'Aldroiti',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1289, 1,1289,'Andemio',0);
 
 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1290, 1,1290,'Antonio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1291, 1,1291,'Andrés',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1292, 1,1292,'Argemiro',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1293, 1,1293,'Artemio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1294, 1,1294,'Bellito',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1295, 1,1295,'Cesario',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1296, 1,1296,'Donnel',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1297, 1,1297,'Egas',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1298, 1,1298,'Eugenio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1299, 1,1299,'Framila',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1300, 1,1300,'Galindo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1301, 1,1301,'Garvisso',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1302, 1,1302,'Goméz',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1303, 1,1303,'Gontino',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1304, 1,1304,'Iderales',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1305, 1,1305,'Lupi',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1306, 1,1306,'Lope',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1307, 1,1307,'Mahemutus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1308, 1,1308,'Martín',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1309, 1,1309,'Nino',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1310, 1,1310,'Máximo',0);
 INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1311, 1,1311,'Olemundo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1312, 1,1312,'Pater',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1313, 1,1313,'Quirico',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1314, 1,1314,'Rademundo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1315, 1,1315,'Ranemundo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1316, 1,1316,'Sabarico',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1317, 1,1317,'Sendino',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1318, 1,1318,'Rodrigo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1319, 1,1319,'Sereno',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1320, 1,1320,'Severo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1321, 1,1321,'Sigerico',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1322, 1,1322,'Sisberto',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1323, 1,1323,'Tello',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1324, 1,1324,'Vistia',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1325, 1,1325,'Vistremiro',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1326, 1,1326,'Jimeno',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1327, 1,1327,'Zalama',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1328, 1,1328,'Abaiub',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1329, 1,1329,'Aboharon',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1330, 1,1330,'Abolus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1331, 1,1331,'Alberto',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1332, 1,1332,'Pelayo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1333, 1,1333,'Abundantius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1334, 1,1334,'Adulfo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1335, 1,1335,'Aiaz',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1336, 1,1336,'Adaiuti',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1337, 1,1337,'Adileubo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1338, 1,1338,'Adoarius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1339, 1,1339,'Agane',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1340, 1,1340,'Agilo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1341, 1,1341,'Aiaz',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1342, 1,1342,'Ailare',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1343, 1,1343,'Alario',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1344, 1,1344,'Albino',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1345, 1,1345,'Aldereto',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1346, 1,1346,'Almundar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1347, 1,1347,'Aliember',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1348, 1,1348,'Artulfo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1349, 1,1349,'Amar',0);
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1350, 1,1350,'Ambrino',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1351, 1,1351,'Ambroz',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1352, 1,1352,'Anastasio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1353, 1,1353,'Ansuro',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1354, 1,1354,'Apidio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1355, 1,1355,'Aragildo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1356, 1,1356,'Aragonti',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1357, 1,1357,'Aresindo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1358, 1,1358,'Argibaio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1359, 1,1359,'Argifredo',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1360, 1,1360,'Nunnus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1361, 1,1361,'Favila',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1362, 1,1362,'Alfonso',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1363, 1,1363,'Alonso',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1364, 1,1364,'Zacarias',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1365, 1,1365,'Zeit',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1366, 1,1366,'Kazem',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1367, 1,1367,'Hodman',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1368, 1,1368,'Abgalip',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1369, 1,1369,'Kazan',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1370, 1,1370,'Zait',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1371, 1,1371,'Dominico',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1372, 1,1372,'Dominicus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1373, 1,1373,'Adefonsus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1374, 1,1374,'Fruela',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1375, 1,1375,'Froilane',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1376, 1,1376,'Abdius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1377, 1,1377,'Abdie',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1378, 1,1378,'Laurentius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1379, 1,1379,'Lorenzo',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1380, 1,1380,'Lubila',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1381, 1,1381,'Zaccarias',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1382, 1,1382,'Ramellus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1383, 1,1383,'Meliki',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1384, 1,1384,'Muzza',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1385, 1,1385,'Domno',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1386, 1,1386,'Melic',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1387, 1,1387,'Hisccam',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1388, 1,1388,'Hazme',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1389, 1,1389,'Aila',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1390, 1,1390,'Medoma',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1391, 1,1391,'Alfidius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1392, 1,1392,'Ziton',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1393, 1,1393,'Zakarias',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1394, 1,1394,'Gali',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1395, 1,1395,'Tomás',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1396, 1,1396,'Rosendo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1397, 1,1397,'Gemondo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1398, 1,1398,'Abdimelque',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1399, 1,1399,'Hilal',0);
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1400, 1,1400,'Osorio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1401, 1,1401,'Guntrodo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1402, 1,1402,'Velasco',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1403, 1,1403,'Suero',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1404, 1,1404,'Vela',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1405, 1,1405,'Flaín',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1406, 1,1406,'Vigila',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1407, 1,1407,'Munio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1408, 1,1408,'Froila',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1409, 1,1409,'Armentario',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1410, 1,1410,'Amor',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1411, 1,1411,'Aznaro',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1412, 1,1412,'Arias',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1413, 1,1413,'Auderico',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1414, 1,1414,'Cresconio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1415, 1,1415,'Ederoño',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1416, 1,1416,'Fagildo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1417, 1,1417,'Fernán',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1418, 1,1418,'Osoro',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1419, 1,1419,'Gelmiro',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1420, 1,1420,'Guter',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1421, 1,1421,'Jimeno',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1422, 1,1422,'Jorge',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1423, 1,1423,'Lugo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1424, 1,1424,'Menendo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1425, 1,1425,'Ordoño',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1426, 1,1426,'Osmundo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1427, 1,1427,'Ramón',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1428, 1,1428,'Salvador',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1429, 1,1429,'Sarracino',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1430, 1,1430,'Telo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1431, 1,1431,'Vimaro',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1432, 1,1432,'Vellito',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1433, 1,1433,'Perucho',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1434, 1,1434,'Perico',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1435, 1,1435,'Pero',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1436, 1,1436,'Per',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1437, 1,1437,'Hernando',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1438, 1,1438,'Hernan',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1439, 1,1439,'Gonzalo',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1440, 1,1440,'Antón',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1441, 1,1441,'Bartolomé',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1442, 1,1442,'Cristobal',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1443, 1,1443,'Ruy',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1444, 1,1444,'Gerónimo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1445, 1,1445,'Sebastian',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1446, 1,1446,'Jayme',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1447, 1,1447,'Yñigo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1448, 1,1448,'Iñigo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1449, 1,1449,'Enrique',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1450, 1,1450,'Henrrique',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1451, 1,1451,'Anrique',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1452, 1,1452,'Nicolás',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1453, 1,1453,'Nicolao',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1454, 1,1454,'Blas',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1455, 1,1455,'Gabriel',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1456, 1,1456,'Guillén',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1457, 1,1457,'Beltrán',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1458, 1,1458,'Beltrané',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1459, 1,1459,'Estevan',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1460, 1,1460,'Bicençio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1461, 1,1461,'Viçente',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1462, 1,1462,'Mateo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1463, 1,1463,'Gutierre',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1464, 1,1464,'Gutirre',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1465, 1,1465,'Gaspar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1466, 1,1466,'Pablo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1467, 1,1467,'Benito',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1468, 1,1468,'Benedicto',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1469, 1,1469,'Fadrique',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1470, 1,1470,'Julián',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1471, 1,1471,'Mendo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1472, 1,1472,'Pascual',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1473, 1,1473,'Simón',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1474, 1,1474,'Ximon',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1475, 1,1475,'Alexandre',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1476, 1,1476,'Alixandre',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1477, 1,1477,'Agustín',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1478, 1,1478,'Agostín',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1479, 1,1479,'Almeyque',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1480, 1,1480,'Almerique',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1481, 1,1481,'Arnao',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1482, 1,1482,'Bernardino',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1483, 1,1483,'Carlos',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1484, 1,1484,'Çino',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1485, 1,1485,'Damián',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1486, 1,1486,'Gascón',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1487, 1,1487,'Hortun',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1488, 1,1488,'Hortuño',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1489, 1,1489,'Lucas',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1490, 1,1490,'Machin',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1491, 1,1491,'Remero',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1492, 1,1492,'Tristán',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1493, 1,1493,'Alsén',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1494, 1,1494,'Altar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1495, 1,1495,'Ambrosio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1496, 1,1496,'Anselmo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1497, 1,1497,'Audres',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1498, 1,1498,'Baltasar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1499, 1,1499,'Bitores',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1500, 1,1500,'Blay',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1501, 1,1501,'Borredan',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1502, 1,1502,'Braçayda',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1503, 1,1503,'Brahen',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1504, 1,1504,'Cosme',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1505, 1,1505,'Donis',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1506, 1,1506,'Duran',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1507, 1,1507,'Ettor',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1508, 1,1508,'Fulgencio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1509, 1,1509,'Galla',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1510, 1,1510,'Gilete',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1511, 1,1511,'Golarte',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1512, 1,1512,'Larnaz',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1513, 1,1513,'Lono',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1514, 1,1514,'Lucon',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1515, 1,1515,'Marçal',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1516, 1,1516,'Marcial',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1517, 1,1517,'Menaute',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1518, 1,1518,'Millán',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1519, 1,1519,'Muli',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1520, 1,1520,'Nofre',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1521, 1,1521,'Nufro',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1522, 1,1522,'Onorato',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1523, 1,1523,'Ontañon',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1524, 1,1524,'Porico',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1525, 1,1525,'Tenorio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1526, 1,1526,'Toribio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1527, 1,1527,'Valeriano',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1528, 1,1528,'Vernaldino',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1529, 1,1529,'Ydalla',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1530, 1,1530,'Samuel',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1531, 1,1531,'Juceph',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1532, 1,1532,'Saúl',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1533, 1,1533,'Mosse',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1534, 1,1534,'Haym',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1535, 1,1535,'Essua',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1536, 1,1536,'Saloru',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1537, 1,1537,'Escachiza',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1538, 1,1538,'Zulema',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1539, 1,1539,'Salamon',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1540, 1,1540,'Falco',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1541, 1,1541,'Crequies',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1542, 1,1542,'Jacob',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1543, 1,1543,'Isaac',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1544, 1,1544,'Estero',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1545, 1,1545,'Nataniel',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1546, 1,1546,'Nasan',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1547, 1,1547,'Vidal',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1548, 1,1548,'Mauregato',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1549, 1,1549,'Nepociano',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1550, 1,1550,'Ato',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1551, 1,1551,'Atterico',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1552, 1,1552,'Bacario',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1553, 1,1553,'Balla',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1554, 1,1554,'Beáto',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1555, 1,1555,'Bera',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1556, 1,1556,'Bolimiro',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1557, 1,1557,'Cereial',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1558, 1,1558,'Citi',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1559, 1,1559,'Conantio',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1560, 1,1560,'Cosendino',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1561, 1,1561,'Deodato',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1562, 1,1562,'Deodavi',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1563, 1,1563,'Eldo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1564, 1,1564,'Elza',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1565, 1,1565,'Felzano',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1566, 1,1566,'Floridio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1567, 1,1567,'Elpidio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1568, 1,1568,'Ulpiano',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1569, 1,1569,'Foracasas',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1570, 1,1570,'Fornario',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1571, 1,1571,'Ermildo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1572, 1,1572,'Evare',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1573, 1,1573,'Iscipio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1574, 1,1574,'Imila',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1575, 1,1575,'Heliseo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1576, 1,1576,'Leodibico',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1577, 1,1577,'Lubla',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1578, 1,1578,'Isciame',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1579, 1,1579,'Manulfo',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1580, 1,1580,'Maurbano',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1581, 1,1581,'Gebuldo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1582, 1,1582,'Guisello',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1583, 1,1583,'Hildosindo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1584, 1,1584,'Gregorio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1585, 1,1585,'Genadio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1586, 1,1586,'Gemel',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1587, 1,1587,'Iaquinto',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1588, 1,1588,'Gomesindo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1589, 1,1589,'Guamiro',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1590, 1,1590,'Guttier',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1591, 1,1591,'Mauronto',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1592, 1,1592,'Monioni',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1593, 1,1593,'Oranio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1594, 1,1594,'Pastor',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1595, 1,1595,'Presentio',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1596, 1,1596,'Quenta',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1597, 1,1597,'Rexindo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1598, 1,1598,'Rattero',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1599, 1,1599,'Recadero',0);
 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1600, 1,1600,'Romano',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1601, 1,1601,'Sabiano',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1602, 1,1602,'Sando',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1603, 1,1603,'Sereniano',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1604, 1,1604,'Sonna',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1605, 1,1605,'Tagel',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1606, 1,1606,'Teodino',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1607, 1,1607,'Valdeo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1608, 1,1608,'Visando',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1609, 1,1609,'Probo',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1610, 1,1610,'Pruenze',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1611, 1,1611,'Johan',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1612, 1,1612,'Domengo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1613, 1,1613,'Pelay',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1614, 1,1614,'Miguel',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1615, 1,1615,'Didaco',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1616, 1,1616,'Isidro',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1617, 1,1617,'Esidro',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1618, 1,1618,'Arnal',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1619, 1,1619,'Durant',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1620, 1,1620,'Benaitu',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1621, 1,1621,'Helias',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1622, 1,1622,'Pelegrin',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1623, 1,1623,'Xab',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1624, 1,1624,'Micholas',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1625, 1,1625,'Facundo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1626, 1,1626,'Gusberto',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1627, 1,1627,'Correnbalde',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1628, 1,1628,'Pay',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1629, 1,1629,'Guiral',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1630, 1,1630,'Ildefonso',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LN',1631, 1,1631,'Goto',0);
 
 

