
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3724, 1,3724,'Ingolfur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3725, 1,3725,'Naddoddr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3726, 1,372,'Gardar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3727, 1,3727,'Haraldur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3728, 1,3728,'Klaengur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3729, 1,3729,'Vilbaldr',0);


INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3730, 1,3730,'Haakon',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3731, 1,3731,'Jon',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3732, 1,3732,'Erik',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3733, 1,3733,'Olafur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3734, 1,3734,'Eidur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3735, 1,3735,'Gudbjartur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3736, 1,3736,'Leif',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3737, 1,3737,'Olaf',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3738, 1,3738,'Olaus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3739, 1,3739,'Magnus',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3740, 1,3740,'Gustav',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3741, 1,3741,'Ari',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3742, 1,3742,'Cyr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3743, 1,3743,'Teitur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3744, 1,3744,'Isleifur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3745, 1,3745,'Kjarvalr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3746, 1,3746,'Gardar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3747, 1,3747,'Floki',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3748, 1,3748,'Hrafna',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3749, 1,3749,'Nattfari',0);
 

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3750, 1,3750,'Porgeirr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3751, 1,3751,'Sturla',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3752, 1,3752,'Thordur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3753, 1,3753,'Sighvatur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3754, 1,3754,'Snorri',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3755, 1,3755,'Sveinn',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3756, 1,3756,'Aedan',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3757, 1,3757,'Uni',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3758, 1,3758,'Thorgeir',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3759, 1,3759,'Bragi',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3760, 1,3760,'Egil',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3761, 1,3761,'Hallfredr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3762, 1,3762,'Einar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3763, 1,3763,'Hallgrimur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3764, 1,3764,'Arngrimur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3765, 1,3765,'Egger',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3766, 1,3766,'Bjarni',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3767, 1,3767,'Jonas',0);
 INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3768, 1,3768,'Steingrimur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3769, 1,3769,'Sigurdun',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3770, 1,3770,'Hjalmar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3771, 1,3771,'Gunnar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3772, 1,3772,'Halldor',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3773, 1,3773,'Agnar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3774, 1,3774,'Thor',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3775, 1,3775,'Molda',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3776, 1,3776,'Gnupur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3777, 1,3777,'Thorir',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3778, 1,3778,'David',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3779, 1,3779,'Petur',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3780, 1,3780,'Thorarinn',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3781, 1,3781,'Saemundr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3782, 1,3782,'Brynjonful',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3783, 1,3783,'Eggert',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3784, 1,3784,'Olafr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3785, 1,3785,'Bersi',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3786, 1,3786,'Thorbjorn',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3787, 1,3787,'Harald',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3788, 1,3788,'Eirkir',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3789, 1,3789,'Canuto',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3790, 1,3790,'Cnut',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3791, 1,3791,'Egill',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3792, 1,3792,'Thjodolfr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3793, 1,3793,'Eyvindir',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3794, 1,3794,'Kormakr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3795, 1,3795,'Eilifr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3796, 1,3796,'Thorvaldr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3797, 1,3797,'Ulfr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3798, 1,3798,'Tidr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3799, 1,3799,'Gunnlagr',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3800, 1,3800,'Sigvart',0);
 INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3801, 1,3801,'Thorarinn',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3802, 1,3802,'Ottarr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3803, 1,3803,'Arnorr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3804, 1,3804,'Einarr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3805, 1,3805,'Thorir',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3806, 1,3806,'Halfdan',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3807, 1,3807,'Guttorn',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3808, 1,3808,'Halvdan',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3809, 1,3809,'Sigrod',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3810, 1,3810,'Alov',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3811, 1,3811,'Rorek',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3812, 1,3812,'Sigtrygg',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3813, 1,3813,'Torgils',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3814, 1,3814,'Ragnar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3815, 1,3815,'Ring',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3816, 1,3816,'Dag',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3817, 1,3817,'Kolbeinn',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3818, 1,3818,'Gunnbjorn',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3819, 1,3819,'Sveinbjorn',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3820, 1,3820,'Thorsteinn',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3821, 1,3821,'Bjorgolfur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3822, 1,3822,'Hreidar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3823, 1,3823,'Arnaldur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3824, 1,3824,'Arsaphius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3825, 1,3825,'Asmundur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3826, 1,3826,'Asbadus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3827, 1,3827,'Bjorgvin',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3828, 1,3828,'Eirikur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3829, 1,3829,'Fridik',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3830, 1,3830,'Gisli',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3831, 1,3831,'Gudrun',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3832, 1,3832,'Hafdis',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3833, 1,3833,'Knut',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3834, 1,3834,'Oystein',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3835, 1,3835,'Sigurd',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3836, 1,3836,'Sverre',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3837, 1,3837,'Bjarni',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3838, 1,3838,'Thorvald',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3839, 1,3839,'Askold',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3840, 1,3840,'Brodir',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3841, 1,3841,'Sweyn',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3842, 1,3842,'Harold',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3843, 1,3843,'Godfrid',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3844, 1,3844,'Grimur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3845, 1,3845,'Guthrum',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3846, 1,3846,'Hastein',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3847, 1,3847,'Ingvar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3848, 1,3848,'Ivar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3849, 1,3849,'Rollo',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3850, 1,3850,'Rurik',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3851, 1,3851,'Rorik',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3852, 1,3852,'Thorgils',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3853, 1,3853,'Thorgest',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3854, 1,3854,'Trondur',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3855, 1,3855,'Asketil',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3856, 1,3856,'Anchitel',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3857, 1,3857,'Anketel',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3858, 1,3858,'Anketin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3859, 1,3859,'Anschitillus',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3860, 1,3860,'Osketel',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3861, 1,3861,'Oskell',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3862, 1,3862,'Yric',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3863, 1,3863,'Ericus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3864, 1,3864,'Acun',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3865, 1,3865,'Hacon',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3866, 1,3866,'Damianus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3867, 1,3867,'Gemmel',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3868, 1,3868,'Nutt',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3869, 1,3869,'Nott',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3870, 1,3870,'Canute',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3871, 1,3871,'Canutus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3872, 1,3872,'Nutkin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3873, 1,3873,'Torold',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3874, 1,3874,'Thorold',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3875, 1,3875,'Thorald',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3876, 1,3876,'Thorkill',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3877, 1,3877,'Torstein',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3878, 1,3878,'Eirikur',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3879, 1,3879,'Olafur',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3880, 1,3880,'Kristofer',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3881, 1,3881,'Karl',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3882, 1,3882,'Kristjan',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3883, 1,3883,'Njall',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3884, 1,3884,'Ljotr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3885, 1,3885,'Rognvaldr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3886, 1,3886,'Sumarlidi',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3887, 1,3887,'Ulfjotr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3888, 1,3888,'Grimr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3889, 1,3889,'Thordis',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3890, 1,3890,'Thorlakur',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3891, 1,3891,'Klaengur',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3892, 1,3892,'Pall',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3893, 1,3893,'Gyrdir',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3894, 1,3894,'Oddgeir',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3895, 1,3895,'Mikael',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3896, 1,3896,'Vilchin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3897, 1,3897,'Ogumundur',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3898, 1,3898,'Marteinn',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3899, 1,3899,'Gisli',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3900, 1,3900,'Brynjolfur',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3901, 1,3901,'Finnur',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3902, 1,3902,'Hannes',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3903, 1,3903,'Haukr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3904, 1,3904,'Geirmundr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3905, 1,3905,'Kolbeinn',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3906, 1,3906,'Brandur',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3907, 1,3907,'Eyjolfur',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3908, 1,3908,'Hallvardur',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3909, 1,3909,'Kalfr',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3910, 1,3910,'Jarl',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3911, 1,3911,'Bodvar',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3912, 1,3912,'Oraekja',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3913, 1,3913,'Urokja',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3914, 1,3914,'Torleiv',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3915, 1,3915,'Hallveig',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3916, 1,3916,'Klaeing',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3917, 1,3917,'Orm',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3918, 1,3918,'Thorolf',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3919, 1,3919,'Aralt',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3920, 1,3920,'Maccus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3921, 1,3921,'Gofraid',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3922, 1,3922,'Yricius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3923, 1,3923,'Ragnald',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3924, 1,3924,'Reginaldus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3925, 1,3925,'Ketill',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3926, 1,3926,'Botolfur',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3927, 1,3927,'Heinrekur',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3928, 1,3928,'Jorundur',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3929, 1,3929,'Audunn',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3930, 1,3930, 'Ormur',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3931, 1,3931,'Larentius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3932, 1,3932,'Gottskalk',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3933, 1,3933,'Smidur',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3934, 1,3934,'Jorgen',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3935, 1,3935,'Thangbrand',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3936, 1,3936,'Thorgnyr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3937, 1,3937,'Gunnlaugr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3938, 1,3938,'Hfran',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3939, 1,3939,'Stuf',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3940, 1,3940,'Helgi',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3941, 1,3941,'Finnbogi',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3942, 1,3942,'Osten',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3943, 1,3943,'Erpr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3944, 1,3944,'Dvalin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3945, 1,3945,'Durin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3946, 1,3946,'Svafrlami',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3947, 1,3947,'Arngrim',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3948, 1,3948,'Angantyr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3949, 1,3949,'Ovar',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3950, 1,3950,'Odd',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3951, 1,3951,'Teodoacro',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3952, 1,3952,'Heidrek',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3953, 1,3953,'Hlod',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3954, 1,3954,'Hermanaricus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3955, 1,3955,'Jormund',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3956, 1,3956,'Tormod',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3957, 1,3957,'Olof',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3958, 1,3958,'Skafti',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3959, 1,3959,'Vigfyss',0); 
  
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3960, 1,3960,'Oddr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3961, 1,3961,'Eyjolfr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3962, 1,3962,'Halldorr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3963, 1,3963,'Thordr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3964, 1,3964,'Harthacnut',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3965, 1,3965,'Thorjell',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3966, 1,3966,'Eadric',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3967, 1,3967,'Anund',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3968, 1,3968,'Godwinus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3969, 1,3969,'Eadgils',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3970, 1,3970,'Onela',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3971, 1,3971,'Ohthere',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3972, 1,3972,'Ottar',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3973, 1,3973,'Alrik',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3974, 1,3974,'Tryggve',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3975, 1,3975,'Thurgestr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3976, 1,3976,'Thorgirsl',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3977, 1,3977,'Tumi',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3978, 1,3978,'Gissur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3979, 1,3979,'Snaebjorn',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3980, 1,3980,'Freydus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3981, 1,3981,'Bjarni',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3982, 1,3982,'Bjorgvin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3983, 1,3983,'Inge',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3984, 1,3984,'Ingi',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3985, 1,3985,'Sverrir',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3986, 1,3986,'Birger',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3987, 1,3987,'Oystein',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3988, 1,3988,'Eirling',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3989, 1,3989,'Nikolas',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3990, 1,3990,'Tore',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3991, 1,3991,'Reidar',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3992, 1,3992,'Swegen',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3993, 1,3993,'Tuck',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3994, 1,3994,'Gudfrid',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3995, 1,3995,'Geir',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3996, 1,3996,'Sigurgeir',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3997, 1,3997,'Thorolf',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3998, 1,3998,'Hallur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',3999, 1,3999,'Yngvi',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4000, 1,4000,'Njordor',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4001, 1,4001,'Freyr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4002, 1,4002,'Fjolnir',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4003, 1,4003,'Vanlandi',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4004, 1,4004,'Visburr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4005, 1,4005,'Svegdir',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4006, 1,4006,'Domaldr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4007, 1,4007,'Domarr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4008, 1,4008,'Dyggvi',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4009, 1,4009,'Dagr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4010, 1,4010,'Alrekr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4011, 1,4011,'Agni',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4012, 1,4012,'Jorundr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4013, 1,4013,'Aun',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4014, 1,4014,'Braut',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4015, 1,4015,'Onundr',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4016, 1,4016,'Healfdene',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4017, 1,4017,'Eanmund',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4018, 1,4018,'Thorlac',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4019, 1,4019,'Eyjolfur',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4020, 1,4020,'Bolli',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4021, 1,4021,'Tostig',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4022, 1,4022,'Gyrd',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4023, 1,4023,'Leofwine',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4024, 1,4024,'Thraell',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4025, 1,4025,'Thir',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4026, 1,4026,'Hedrel',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4027, 1,4027,'Ingjaldr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4028, 1,4028,'Ketil',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4029, 1,4029,'Skalla',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_IS',4030, 1,4030,'Hjalti',0);
 
 
 
 
 

