


INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1924, 1,1924,'Clotaire',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1925, 1,1925,'Felix',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1926, 1,1926,'Loup',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1927, 1,1927,'Eudes',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1928, 1,1928,'Hunald',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1929, 1,1929,'Waifre',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1930, 1,1930,'Corson',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1931, 1,1931,'Louis',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1932, 1,1932,'Guillaume',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1933, 1,1933,'Pepin',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1934, 1,1934,'Charles',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1935, 1,1935,'Carloman',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1936, 1,1936,'Ramnulfus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1937, 1,1937,'Acfred',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1938, 1,1938,'Ebles',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1939, 1,1939,'Othon',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1940, 1,1940,'Jeans',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1941, 1,1941,'Henri',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1942, 1,1942,'Edouard',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1943, 1,1943,'Adraldus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1944, 1,1944,'Hacfredus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1945, 1,1945,'Boso',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1946, 1,1946,'Bernard',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1947, 1,1947,'Willelmus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1948, 1,1948,'Cyprien',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1949, 1,1949,'Segoinus',0);
 

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1950, 1,1950,'Caique',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1951, 1,1951,'Leunclavius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1952, 1,1952,'Clergie',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1953, 1,1953,'Ordericus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1954, 1,1954,'Radulfus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1955, 1,1955,'Clericus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1956, 1,1956,'Echalas',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1957, 1,1957,'Garbin',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1958, 1,1958,'Giron',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1959, 1,1959,'Martenel',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1960, 1,1960,'Pierre',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1961, 1,1961,'Claude',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1962, 1,1962,'François',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1963, 1,1963,'Gustave',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1964, 1,1964,'Arlac',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1965, 1,1965,'Andernac',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1966, 1,1966,'Arnay',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1967, 1,1967,'Auriac',0);
 INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1968, 1,1968,'Balirac',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1969, 1,1969,'Bernay',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1970, 1,1970,'Arnus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1971, 1,1971,'Arnasco',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1972, 1,1972,'Arnate',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1973, 1,1973,'Burnus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1974, 1,1974,'Carnus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1975, 1,1975,'Carius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1976, 1,1976,'Basius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1977, 1,1977,'Calvinius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1978, 1,1978,'Cavallius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1979, 1,1979,'Lanius',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1980, 1,1980,'Vercius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1981, 1,1981,'Billos',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1982, 1,1982,'Buros',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1983, 1,1983,'Cizos',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1984, 1,1984,'Cardos',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1985, 1,1985,'Agos',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1986, 1,1986,'Colombots',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1987, 1,1987,'Dalhos',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1988, 1,1988,'Gallues',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1989, 1,1989,'Payros',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1990, 1,1990,'Virues',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1991, 1,1991,'Andossus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1992, 1,1992,'Apinossus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1993, 1,1993,'Billicatus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1994, 1,1994,'Bortossus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1995, 1,1995,'Cacus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1996, 1,1996,'Clamossus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1997, 1,1997,'Condianus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1998, 1,1998,'Odannus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',1999, 1,1999,'Sappulo',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2000, 1,2000,'Allius',0);
 INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2001, 1,2001,'Illos',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2002, 1,2002,'Aurelius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2003, 1,2003,'Aurelianus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2004, 1,2004,'Dominitianus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2005, 1,2005,'Julianus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2006, 1,2006,'Martius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2007, 1,2007,'Octavianus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2008, 1,2008,'Avitus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2009, 1,2009,'Acco',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2010, 1,2010,'Annius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2011, 1,2011,'Alotze',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2012, 1,2012,'Foulques',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2013, 1,2013,'Sanche',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2014, 1,2014,'Raoul',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2015, 1,2015,'Savari',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2016, 1,2016,'Geraud',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2017, 1,2017,'Rohon',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2018, 1,2018,'Gislebert',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2019, 1,2019,'Isembert',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2020, 1,2020,'Geoffroy',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2021, 1,2021,'Radulfus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2022, 1,2022,'Aimeri',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2023, 1,2023,'Cybard',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2024, 1,2024,'Hugues',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2025, 1,2025,'Ademar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2026, 1,2026,'Reanud',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2027, 1,2027,'Boggis',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2028, 1,2028,'Waifar',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2029, 1,2029,'Hatto',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2030, 1,2030,'Artgarius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2031, 1,2031,'Antoine',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2032, 1,2032,'Emiladius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2033, 1,2033,'Icterius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2034, 1,2034,'Remistan',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2035, 1,2035,'Bego',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2036, 1,2036,'Ebalus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2037, 1,2037,'Eble',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2038, 1,2038,'Etienne',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2039, 1,2039,'Abbon',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2040, 1,2040,'Richwinus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2041, 1,2041,'Emenon',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2042, 1,2042,'Adalelm',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2043, 1,2043,'Tedericus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2044, 1,2044,'Balduinus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2045, 1,2045,'Chuonradus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2046, 1,2046,'Turpinus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2047, 1,2047,'Gerardus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2048, 1,2048,'Ramnulfus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2049, 1,2049,'Robertus',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2050, 1,2050,'Immo',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2051, 1,2051,'Gauzbert',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2052, 1,2052,'Josbert',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2053, 1,2053,'Froterius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2054, 1,2054,'Raino',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2055, 1,2055,'Audebertus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2056, 1,2056,'Thibaut',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2057, 1,2057,'Guy',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2058, 1,2058,'Gaufredus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2059, 1,2059,'Goffredus',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2060, 1,2060,'Trullus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2061, 1,2061,'Raimirus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2062, 1,2062,'Sebrandus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2063, 1,2063,'Jehan',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2064, 1,2064,'Philippot',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2065, 1,2065,'Colin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2066, 1,2066,'Jehemin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2067, 1,2067,'Jaquet',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2068, 1,2068,'Guillot',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2069, 1,2069,'Jehannet',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2070, 1,2070,'Perrenet',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2071, 1,2071,'Perrin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2072, 1,2072,'Robin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2073, 1,2073,'Robinet',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2074, 1,2074,'Thomaz',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2075, 1,2075,'Thommas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2076, 1,2076,'Thommin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2077, 1,2077,'Jaques',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2078, 1,2078,'Nicolas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2079, 1,2079,'Estienot',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2080, 1,2080,'Denis',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2081, 1,2081,'Fremin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2082, 1,2082,'Gassot',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2083, 1,2083,'Geffray',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2084, 1,2084,'George',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2085, 1,2085,'Servando',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2086, 1,2086,'Georges',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2087, 1,2087,'Gerardin',0 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2088, 1,2088,'Germain',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2089, 1,2089,'Guillet',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2090, 1,2090,'Guiot',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2091, 1,2091,'Jacob',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2092, 1,2092,'Lorens',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2093, 1,2093,'Marin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2094, 1,2094,'Michel',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2095, 1,2095,'Noel',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2096, 1,2096,'Nouel',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2097, 1,2097,'Oudin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2098, 1,2098,'Adrian',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2099, 1,2099,'Alain',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2100, 1,2100,'Alan',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2101, 1,2101,'Alexandre',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2102, 1,2102,'Alphonse',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2103, 1,2103,'Armand',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2104, 1,2104,'Amaniou',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2105, 1,2105,'Amanyou',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2106, 1,2106,'Ambroys',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2107, 1,2107,'Andre',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2108, 1,2108,'Anraud',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2109, 1,2109,'Anthony',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2110, 1,2110,'Armel',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2111, 1,2111,'Arnold',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2112, 1,2112,'Ascoet',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2113, 1,2113,'Audet',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2114, 1,2114,'Augier',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2115, 1,2115,'Balthasar',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2116, 1,2116,'Bartholomew',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2117, 1,2117,'Basilles',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2118, 1,2118,'Baudoin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2119, 1,2119,'Benedict',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2120, 1,2120,'Berdot',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2121, 1,2121,'Berenger',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2122, 1,2122,'Bernuy',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2123, 1,2123,'Bertrand',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2124, 1,2124,'Blasy',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2125, 1,2125,'Boniface',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2126, 1,2126,'Brunet',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2127, 1,2127,'Christofle',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2128, 1,2128,'Clemaret',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2129, 1,2129,'Cletio',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2130, 1,2130,'Compaheto',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2131, 1,2131,'Corantin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2132, 1,2132,'Corneille',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2133, 1,2133,'Daniel',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2134, 1,2134,'Durand',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2135, 1,2135,'Duras',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2136, 1,2136,'Eugramet',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2137, 1,2137,'Fiacre',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2138, 1,2138,'Florens',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2139, 1,2139,'Fort',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2140, 1,2140,'Fouques',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2141, 1,2141,'Gabriel',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2142, 1,2142,'Gailhard',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2143, 1,2143,'Garsiarnaud',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2144, 1,2144,'Gaspar',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2145, 1,2145,'Gaston',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2146, 1,2146,'Gaubert',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2147, 1,2147,'Gaucemot',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2148, 1,2148,'Grolamme',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2149, 1,2149,'Govyn',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2150, 1,2150,'Gratian',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2151, 1,2151,'Guerbrand',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2152, 1,2152,'Guerard',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2153, 1,2153,'Guissarnaud',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2154, 1,2154,'Guyon',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2155, 1,2155,'Guynole',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2156, 1,2156,'Hamon',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2157, 1,2157,'Hector',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2158, 1,2158,'Helias',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2159, 1,2159,'Herve',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2160, 1,2160,'Hillaire',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2161, 1,2161,'Huget',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2162, 1,2162,'Huginot',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2163, 1,2163,'Jacmes',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2164, 1,2164,'Jehacon',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2165, 1,2165,'Jherome',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2166, 1,2166,'Jodoicus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2167, 1,2167,'Josse',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2168, 1,2168,'Lambert',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2169, 1,2169,'Laurens',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2170, 1,2170,'Legier',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2171, 1,2171,'Leonard',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2172, 1,2172,'Loys',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2173, 1,2173,'Louis',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2174, 1,2174,'Mace',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2175, 1,2175,'Machicho',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2176, 1,2176,'Marc',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2177, 1,2177,'Marotine',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2178, 1,2178,'Mathias',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2179, 1,2179,'Mathieu',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2180, 1,2180,'Mathurin',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2181, 1,2181,'Menault',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2182, 1,2182,'Mery',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2183, 1,2183,'Morice',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2184, 1,2184,'Mynjon',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2185, 1,2185,'Naudin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2186, 1,2186,'Nycholas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2187, 1,2187,'Olivier',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2188, 1,2188,'Paciot',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2189, 1,2189,'Pascault',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2190, 1,2190,'Patris',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2191, 1,2191,'Philibert',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2192, 1,2192,'Phelip',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2193, 1,2193,'Pitres',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2194, 1,2194,'Poul',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2195, 1,2195,'Raphael',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2196, 1,2196,'Regner',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2197, 1,2197,'Remy',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2198, 1,2198,'Richard',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2199, 1,2199,'Rional',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2200, 1,2200,'Riou',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2201, 1,2201,'Robert',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2202, 1,2202,'Roubin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2203, 1,2203,'Roderigo',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2204, 1,2204,'Rogier',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2205, 1,2205,'Roullaud',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2206, 1,2206,'Saulvat',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2207, 1,2207,'Saussin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2208, 1,2208,'Sebastien',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2209, 1,2209,'Seguyn',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2210, 1,2210,'Simon',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2211, 1,2211,'Thierry',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2212, 1,2212,'Tillyman',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2213, 1,2213,'Tristand',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2214, 1,2214,'Tustan',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2215, 1,2215,'Tymen',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2216, 1,2216,'Valentine',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2217, 1,2217,'Vidault',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2218, 1,2218,'Verdot',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2219, 1,2219,'Viron',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2220, 1,2220,'Ythier',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2221, 1,2221,'Yvon',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2222, 1,2222,'Vincent',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2223, 1,2223,'Yzabram',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2224, 1,2224,'Gondowald',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_AQ',2225, 1,2225,'Caribert',0);

