
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3440, 1,3440,'Alisandre',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3441, 1,3441,'Alisaunder',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3442, 1,3442,'Eck',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3443, 1,3443,'Elexander',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3444, 1,3444,'Elysandre',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3445, 1,3445,'Alsandre',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3446, 1,3446,'Basil',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3447, 1,3447,'Basilius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3448, 1,3448,'Basileus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3449, 1,3449,'Chrysogon',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3450, 1,3450,'Grisigion',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3451, 1,3451,'Chrysogonus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3452, 1,3452,'Cyr',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3453, 1,3453,'Cirilus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3454, 1,3454,'Cyriack',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3455, 1,3455,'Denis',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3456, 1,3456,'Denes',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3457, 1,3457,'Dionisius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3458, 1,3458,'Dyonisius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3459, 1,3459,'Eustachius',0);
 

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3460, 1,3460,'Eustaicus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3461, 1,3461,'Eustache',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3462, 1,3462,'Eustas',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3463, 1,3463,'Georgius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3464, 1,3464,'Georgus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3465, 1,3465,'Gregorius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3466, 1,3466,'Hector',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3467, 1,3467,'Hippolytus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3468, 1,3468,'Ippolitus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3469, 1,3469,'Ypolitus',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3470, 1,3470,'Ignatius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3471, 1,3471,'Jenico',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3472, 1,3472,'Philippus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3473, 1,3473,'Philipon',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3474, 1,3474,'Philkin',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3475, 1,3475,'Albrecht',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3476, 1,3476,'Pip',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3477, 1,3477,'Constantinus',0);
 INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3478, 1,3478,'Kostan',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3479, 1,3479,'Valentius',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3480, 1,3480,'Arcadius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3481, 1,3481,'Theodosius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3482, 1,3482,'Zeno',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3483, 1,3483,'Romulus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3484, 1,3484,'Augustus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3485, 1,3485,'Heraclius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3486, 1,3486,'Anastasius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3487, 1,3487,'Marcianus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3488, 1,3488,'Leo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3489, 1,3489,'Basiliscus',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3490, 1,3490,'Iustino',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3491, 1,3491,'Iustinianus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3492, 1,3492,'Phocas',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3493, 1,3493,'Tiberius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3494, 1,3494,'Heraclonas',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3495, 1,3495,'Constans',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3496, 1,3496,'Leontius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3497, 1,3497,'Philippicus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3498, 1,3498,'Artabasdus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3499, 1,3499,'Stauracius',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3500, 1,3500,'Micaelus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3501, 1,3501,'Micael',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3502, 1,3502,'Michel',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3503, 1,3503,'Michael',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3504, 1,3504,'Theophilus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3505, 1,3505,'Teofilo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3506, 1,3506,'Niceforo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3507, 1,3507,'Leon',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3508, 1,3508,'Basileo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3509, 1,3509,'Constantino',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3510, 1,3510,'Issac',0);
 INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3511, 1,3511,'Alexius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3512, 1,3512,'Alexis',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3513, 1,3513,'Andronico',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3514, 1,3514,'Andronicus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3515, 1,3515,'Manuel',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3516, 1,3516,'Angelus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3517, 1,3517,'Theodore',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3518, 1,3518,'Teodoro',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3519, 1,3519,'Ioannes',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3520, 1,3520,'Paleologo',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3521, 1,3521,'Abramius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3522, 1,3522,'Acindynus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3523, 1,3523,'Agapetus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3524, 1,3524,'Alyattes',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3525, 1,3525,'Amirrutzes',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3526, 1,3526,'Jakobus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3527, 1,3527,'Ampelius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3528, 1,3528,'Anatolicus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3529, 1,3529,'Anatolius',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3530, 1,3530,'Anthemius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3531, 1,3531,'Anthimus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3532, 1,3532,'Arcadius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3533, 1,3533,'Armatus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3534, 1,3534,'Arsaphius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3535, 1,3535,'Arsenius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3536, 1,3536,'Asbadus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3537, 1,3537,'Asterius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3538, 1,3538,'Babylas',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3539, 1,3539,'Bacauda',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3540, 1,3540,'Baduarius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3541, 1,3541,'Basiliakos',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3542, 1,3542,'Batzas',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3543, 1,3543,'Beppolenus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3544, 1,3544,'Boethius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3545, 1,3545,'Bryennius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3546, 1,3546,'Butilinus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3547, 1,3547,'Calopodius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3548, 1,3548,'Cantacuzenes',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3549, 1,3549,'Carellus',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3550, 1,3550,'Charegiselus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3551, 1,3551,'Chilbudius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3552, 1,3552,'Christoboulus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3553, 1,3553,'Laurentius',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3554, 1,3554,'Christophorus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3555, 1,3555,'Chroniates',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3556, 1,3556,'Colluthus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3557, 1,3557,'Comentas',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3558, 1,3558,'Ramnulfus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3559, 1,3559,'Robertus',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3560, 1,3560,'Comentiolus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3561, 1,3561,'Stephanus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3562, 1,3562,'Cometas',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3563, 1,3563,'Comitas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3564, 1,3564,'Comitiolus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3565, 1,3565,'Corippus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3566, 1,3566,'Cosmas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3567, 1,3567,'Cresconius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3568, 1,3568,'Gaufredus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3569, 1,3569,'Goffredus',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3570, 1,3570,'Trullus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3571, 1,3571,'Raimirus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3572, 1,3572,'Sebrandus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3573, 1,3573,'Cyricus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3574, 1,3574,'Cyrul',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3575, 1,3575,'Damasus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3576, 1,3576,'Damianus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3577, 1,3577,'Dorotheus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3578, 1,3578,'Droserius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3579, 1,3579,'Dulcissinius',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3580, 1,3580,'Danielus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3581, 1,3581,'Balduinus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3582, 1,3582,'Didymus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3583, 1,3583,'Diosconis',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3584, 1,3584,'Deuterius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3585, 1,3585,'Engelhardus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3586, 1,3586,'Domentziolus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3587, 1,3587,'Ennodius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3588, 1,3588,'Epiphanius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3589, 1,3589,'Epifanio',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3590, 1,3590,'Eudaemon',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3591, 1,3591,'Eudoxius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3592, 1,3592,'Eulalio',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3593, 1,3593,'Eulampius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3594, 1,3594,'Eulogio',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3595, 1,3595,'Eupatarius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3596, 1,3596,'Eufemio',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3597, 1,3597,'Eupharas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3598, 1,3598,'Euphronius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3599, 1,3599,'Eusebio',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3600, 1,3600,'Eustaquio',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3601, 1,3601,'Eustochius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3602, 1,3602,'Eutychius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3603, 1,3603,'Formosos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3604, 1,3604,'Genethlius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3605, 1,3605,'Gennadio',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3606, 1,3606,'Gallus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3607, 1,3607,'Gerontius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3608, 1,3608,'Hermongenes',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3609, 1,3609,'Iosephus',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3610, 1,3610,'Ireneo',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3611, 1,3611,'Laskaris',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3612, 1,3612,'Isidoro',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3613, 1,3613,'Isaac',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3614, 1,3614,'Habbibalianus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3615, 1,3615,'Domenicus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3616, 1,3616,'Sebastian',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3617, 1,3617,'Hieronymus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3618, 1,3618,'Metodio',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3619, 1,3619,'Menas',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3620, 1,3620,'Moschus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3621, 1,3621,'Olybrius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3622, 1,3622,'Origen',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3623, 1,3623,'Pachymeres',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3624, 1,3624,'Gregoras',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3625, 1,3625,'Nicetius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3626, 1,3626,'Michaelius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3627, 1,3627,'Nazares',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3628, 1,3628,'Nicetas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3629, 1,3629,'Palamas',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3630, 1,3630,'Pamphilus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3631, 1,3631,'Pancratius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3632, 1,3632,'Pardus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3633, 1,3633,'Parthenius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3634, 1,3634,'Pardus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3635, 1,3635,'Pantagathus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3636, 1,3636,'Philoxenus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3637, 1,3637,'Philaretus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3638, 1,3638,'Phoebammon',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3639, 1,3639,'Photinus',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3640, 1,3640, 'Plutinus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3641, 1,3641,'Potamius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3642, 1,3642,'Rogatus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3643, 1,3643,'Sarapammon',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3644, 1,3644,'Satabus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3645, 1,3645,'Scholasticus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3646, 1,3646,'Senuthius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3647, 1,3647,'Simocatta',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3648, 1,3648,'Sittas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3649, 1,3649,'Smaragdus',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3650, 1,3650,'Speciosus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3651, 1,3651,'Stauricius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3652, 1,3652,'Stilicho',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3653, 1,3653,'Strategius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3654, 1,3654,'Syagricus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3655, 1,3655,'Syagrius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3656, 1,3656,'Symeon',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3657, 1,3657,'Symeonius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3658, 1,3658,'Tarchaniotes',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3659, 1,3659,'Theocharistus',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3660, 1,3660,'Theoctistus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3661, 1,3661,'Teodoacro',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3662, 1,3662,'Theodoretus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3663, 1,3663,'Theodoricus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3664, 1,3664,'Theodorus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3665, 1,3665,'Theodulus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3666, 1,3666,'Theogenius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3667, 1,3667,'Theon',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3668, 1,3668,'Theopemptus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3669, 1,3669,'Theophylact',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3670, 1,3670,'Theotimus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3671, 1,3671,'Trasaric',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3672, 1,3672,'Tzimisas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3673, 1,3673,'Tzittas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3674, 1,3674,'Vaanes',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3675, 1,3675,'Varazes',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3676, 1,3676,'Vasacius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3677, 1,3677,'Zemarchus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3678, 1,3678,'Ambricus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3679, 1,3679,'Zeno',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3680, 1,3680,'Zenobius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3681, 1,3681,'Ziper',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3682, 1,3682,'Zoilus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3683, 1,3683,'Acacius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3684, 1,3684,'Achaeus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3685, 1,3685,'Acron',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3686, 1,3686,'Aedesius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3687, 1,3687,'Alexios',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3688, 1,3688,'Andrikopolos',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3689, 1,3689,'Arsenios',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3690, 1,3690,'Demetrios',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3691, 1,3691,'Euthymios',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3692, 1,3692,'Georgios',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3693, 1,3693,'Konstantinos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3694, 1,3694,'Kosmas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3695, 1,3695,'Nikephoros',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3696, 1,3696,'Nikolaos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3697, 1,3697,'Petros',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3698, 1,3698,'Patrikios',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3699, 1,3699,'Philippos',0);
 

 
 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3700, 1,3700,'Ramnatas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3701, 1,3701,'Saratenos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3702, 1,3702,'Sevastos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3703, 1,3703,'Theodoros',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3704, 1,3704,'Vasileos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3705, 1,3705,'Zegros',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3706, 1,3706,'Asemopoulos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3707, 1,3707,'Athanasios',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3708, 1,3708,'Dragos',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3709, 1,3709,'Eleutherios',0);
 

  

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3710, 1,3710,'Foteinos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3711, 1,3711,'Evangelos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3712, 1,3712,'Komanos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3713, 1,3713,'Kyriakos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3714, 1,3714,'Loumbertos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3715, 1,3715,'Modestos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3716, 1,3716,'Myristikos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3717, 1,3717,'Pelekanos',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3718, 1,3718,'Prousenos',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3719, 1,3719,'Theotokios',0);
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3720, 1,3720'Alec',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3721, 1,3721,'Aleck',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3722, 1,3722,'Alesaunder',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_CH',3723, 1,3723,'Alexandir',0);

