
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2226, 1,2226,'Bartolomejs',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2227, 1,2227,'Benedikts',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2228, 1,2228,'Bernards',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2229, 1,2229,'Darbeslave',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2230, 1,2230,'Demas',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2231, 1,2231,'Demetrijs',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2232, 1,2232,'Demiters',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2233, 1,2233,'Dionizijs',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2234, 1,2234,'Dobre',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2235, 1,2235,'Domiane',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2236, 1,2236,'Dominiks',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2237, 1,2237,'Dionizjis',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2238, 1,2238,'Elmede',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2239, 1,2239,'Erasts',0);
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2240, 1,2240,'Fabians',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2241, 1,2241,'Francisks',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2242, 1,2242,'Galeine',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2243, 1,2243,'Gallus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2244, 1,2244,'Gastile',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2245, 1,2245,'Gedere',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2246, 1,2246,'Georgijs',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2247, 1,2247,'Golovke',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2248, 1,2248,'Gotene',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2249, 1,2249,'Gregors',0);
 

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2250, 1,2250,'Hanss',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2251, 1,2251,'Hanse',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2252, 1,2252,'Heinrihs',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2253, 1,2253,'Hence',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2254, 1,2254,'Henneke',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2255, 1,2255,'Henriks',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2256, 1,2256,'Henrikus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2257, 1,2257,'Hermanis',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2258, 1,2258,'Hoelempe',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2259, 1,2259,'Imme',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2260, 1,2260,'Ivans',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2261, 1,2261,'Jakobs',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2262, 1,2262,'Jane',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2263, 1,2263,'Janis',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2264, 1,2264,'Jaunule',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2265, 1,2265,'Johans',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2266, 1,2266,'Jurge',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2267, 1,2267,'Jurgelis',0);
 INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2268, 1,2268,'Juvage',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2269, 1,2269,'Kage',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2270, 1,2270,'Kaire',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2271, 1,2271,'Klavess',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2272, 1,2272,'Klave',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2273, 1,2273,'Klavke',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2274, 1,2274,'Kodere',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2275, 1,2275,'Koders',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2276, 1,2276,'Koms',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2277, 1,2277,'Konrads',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2278, 1,2278,'Kukens',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2279, 1,2279,'Kusemans',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2280, 1,2280,'Kuliens',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2281, 1,2281,'Kurlemuse',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2282, 1,2282,'Litto',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2283, 1,2283,'Macele',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2284, 1,2284,'Martins',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2285, 1,2285,'Meinekinus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2286, 1,2286,'Mihaels',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2287, 1,2287,'Miksa',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2288, 1,2288,'Novsade',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2289, 1,2289,'Peters',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2290, 1,2290,'Peteris',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2291, 1,2291,'Plike',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2292, 1,2292,'Remmeke',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2293, 1,2293,'Rovels',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2294, 1,2294,'Savsede',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2295, 1,2295,'Sayme',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2296, 1,2296,'Sedegovde',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2297, 1,2297,'Simons',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2298, 1,2298,'Abartolmejs',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2299, 1,2299,'Alberts',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2300, 1,2300,'Alfs',0);
 INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2301, 1,2301,'Ambrozijs',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2302, 1,2302,'Andreass',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2303, 1,2303,'Andrejus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2304, 1,2304,'Andress',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2305, 1,2305,'Baise',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2306, 1,2306,'Balodis',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2307, 1,2307,'Bartolds',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2308, 1,2308,'Berns',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2309, 1,2309,'Beltemeus',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2310, 1,2310,'Bertels',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2311, 1,2311,'Bertols',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2312, 1,2312,'Bite',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2313, 1,2313,'Bonifacijs',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2314, 1,2314,'Cirulis',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2315, 1,2315,'Cirulitus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2316, 1,2316,'Davins',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2317, 1,2317,'Dirikis',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2318, 1,2318,'Dumpiaten',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2319, 1,2319,'Dzenitis',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2320, 1,2320,'Everts',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2321, 1,2321,'Fromholds',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2322, 1,2322,'Gothards',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2323, 1,2323,'Hanins',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2324, 1,2324,'Hince',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2325, 1,2325,'Ilarions',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2326, 1,2326,'Kaipe',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2327, 1,2327,'Karusa',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2328, 1,2328,'Jurits',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2329, 1,2329,'Koule',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2330, 1,2330,'Kuris',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2331, 1,2331,'Kurts',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2332, 1,2332,'Labrens',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2333, 1,2333,'Labrins',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2334, 1,2334,'Lacis',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2335, 1,2335,'Ladevihs',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2336, 1,2336,'Lucass',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2337, 1,2337,'Luke',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2338, 1,2338,'Laurens',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2339, 1,2339,'Laurentijs',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2340, 1,2340,'Libite',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2341, 1,2341,'Lidacinna',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2342, 1,2342,'Liva',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2343, 1,2343,'Luke',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2344, 1,2344,'Macgels',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2345, 1,2345,'Melda',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2346, 1,2346,'Mertens',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2347, 1,2347,'Gerardus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2348, 1,2348,'Ramnulfus',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2349, 1,2349,'Robertus',0);

INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2350, 1,2350,'Immo',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2351, 1,2351,'Gauzbert',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2352, 1,2352,'Josbert',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2353, 1,2353,'Froterius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2354, 1,2354,'Mihels',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2355, 1,2355,'Audebertus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2356, 1,2356,'Olafs',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2357, 1,2357,'Price',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2358, 1,2358,'Gaufredus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2359, 1,2359,'Goffredus',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2360, 1,2360,'Trullus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2361, 1,2361,'Raimirus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2362, 1,2362,'Sebrandus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2363, 1,2363,'Ozolins',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2364, 1,2364,'Pantalejmons',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2365, 1,2365,'Pauvels',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2366, 1,2366,'Pesins',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2367, 1,2367,'Prexlow',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2368, 1,2368,'Ragas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2369, 1,2369,'Selis',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2370, 1,2370,'Sergis',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2371, 1,2371,'Sersma',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2372, 1,2372,'Sersnis',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2373, 1,2373,'Simonite',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2374, 1,2374,'Sintels',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2375, 1,2375,'Aulle',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2376, 1,2376,'Antuss',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2377, 1,2377,'Ape',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2378, 1,2378,'Appuls',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2379, 1,2379,'Ars',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2380, 1,2380,'Bargs',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2381, 1,2381,'Azel',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2382, 1,2382,'Bauga',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2383, 1,2383,'Bele',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2384, 1,2384,'Bebers',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2385, 1,2385,'Bortels',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2386, 1,2386,'Cekulis',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2387, 1,2387,'Codors',0 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2388, 1,2388,'Cakste',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2389, 1,2389,'Dabe',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2390, 1,2390,'Aado',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2391, 1,2391,'Anu',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2392, 1,2392,'Edgar',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2393, 1,2393,'Erke',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2394, 1,2394,'Juku',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2395, 1,2395,'Konstantin',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2396, 1,2396,'Tomi',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2397, 1,2397,'Vaino',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2398, 1,2398,'Ahti',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2399, 1,2399,'Arno',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2400, 1,2400,'Elmo',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2401, 1,2401,'Indrek',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2402, 1,2402,'Juri',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2403, 1,2403,'Kristjan',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2404, 1,2404,'Peeter',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2405, 1,2405,'Tonu',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2406, 1,2406,'Valdek',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2407, 1,2407,'Aino',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2408, 1,2408,'Arnold',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2409, 1,2409,'Emil',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2410, 1,2410,'Ivo',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2411, 1,2411,'Kaarel',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2412, 1,2412,'Lauri',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2413, 1,2413,'Rein',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2414, 1,2414,'Tunne',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2415, 1,2415,'Villem',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2416, 1,2416,'Andrei',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2417, 1,2417,'Artier',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2418, 1,2418,'Endel',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2419, 1,2419,'Jaak',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2420, 1,2420,'Kaido',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2421, 1,2421,'Lembit',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2422, 1,2422,'Robertas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2423, 1,2423,'Ulo',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2424, 1,2424,'Andres',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2425, 1,2425,'Andrews',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2426, 1,2426,'Arvo',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2427, 1,2427,'Coomas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2428, 1,2428,'Enel',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2429, 1,2429,'Enn',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2430, 1,2430,'Jaan',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2431, 1,2431,'Johannes',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2432, 1,2432,'Kaupo',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2433, 1,2433,'Koit',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2434, 1,2434,'Mart',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2435, 1,2435,'Mati',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2436, 1,2436,'Tiit',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2437, 1,2437,'Toivo',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2438, 1,2438,'Urmet',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2439, 1,2439,'Urve',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2440, 1,2440,'Aleksander',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2441, 1,2441,'Andrus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2442, 1,2442,'Georg',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2443, 1,2443,'Heino',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2444, 1,2444,'Hendrik',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2445, 1,2445,'Hillar',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2446, 1,2446,'Jaagup',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2447, 1,2447,'Jaak',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2448, 1,2448,'Jaan',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2449, 1,2449,'Johannes',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2450, 1,2450,'Joosep',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2451, 1,2451,'Juhan',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2452, 1,2452,'Kalev',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2453, 1,2453,'Kristjan',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2454, 1,2454,'Mihkel',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2455, 1,2455,'Nigul',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2456, 1,2456,'Olev',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2457, 1,2457,'Paavo',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2458, 1,2458,'Peeter',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2459, 1,2459,'Tonis',0); 
 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2460, 1,2460,'Adolfas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2461, 1,2461,'Almal',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2462, 1,2462,'Andrius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2463, 1,2463,'Algimantas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2464, 1,2464,'Algis',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2465, 1,2465,'Amantas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2466, 1,2466,'Augustinas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2467, 1,2467,'Baltrius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2468, 1,2468,'Antavas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2469, 1,2469,'Bartas',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2470, 1,2470,'Arunas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2471, 1,2471,'Dalius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2472, 1,2472,'Bromius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2473, 1,2473,'Dzidorius',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2474, 1,2474,'Edgarras',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2475, 1,2475,'Feliksas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2476, 1,2476,'Grigas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2477, 1,2477,'Gintautas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2478, 1,2478,'Jounele',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2479, 1,2479,'Ipolitas',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2480, 1,2480,'Linas',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2481, 1,2481,'Kipras',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2482, 1,2482,'Jeronimas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2483, 1,2483,'Karolis',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2484, 1,2484,'Jonas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2485, 1,2485,'Keska',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2486, 1,2486,'Juzos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2487, 1,2487,'Keistutis',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2488, 1,2488,'Leonidas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2489, 1,2489,'Liudas',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2490, 1,2490,'Kasparas',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2491, 1,2491,'Girdenis',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2492, 1,2492,'Juozapas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2493, 1,2493,'Marijus',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2494, 1,2494,'Martynas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2495, 1,2495,'Ricardas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2496, 1,2496,'Provilas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2497, 1,2497,'Rimantas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2498, 1,2498,'Mecislovas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2499, 1,2499,'Micha',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2500, 1,2500,'Paal',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2501, 1,2501,'Michalo',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2502, 1,2502,'Olgierd',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2503, 1,2503,'Mikalos',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2504, 1,2504,'Remis',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2505, 1,2505,'Petras',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2506, 1,2506,'Rosertas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2507, 1,2507,'Samuelis',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2508, 1,2508,'Solomonas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2509, 1,2509,'Stasis',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2510, 1,2510,'Saulius',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2511, 1,2511,'Sharunas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2512, 1,2512,'Tillyman',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2513, 1,2513,'Svitrigaila',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2514, 1,2514,'Tanas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2515, 1,2515,'Tarvydas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2516, 1,2516,'Tomas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2517, 1,2517,'Tomelis',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2518, 1,2518,'Tylenis',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2519, 1,2519,'Viktors',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2520, 1,2520,'Ugnius',0); 
 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2521, 1,2521,'Vaclavas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2522, 1,2522,'Vicas',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2523, 1,2523,'Yanush',0); 
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2524, 1,2524,'Zenonas',0);
INSERT INTO `tablas` (`CODIGO`,`SUBCODIGO`,`IDIOMAID`, `ORDEN`, `DESCRIPCION`, `VALOR`) VALUES ('NOM_LV',2525, 1,2525,'Zigmantas',0);

