INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 1, "R", "15");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 2, "R", "13");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 3, "R", "13");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 4, "R", "12");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 5, "R", "17");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 6, "R", "15");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 7, "R", "12");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 8, "R", "19");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 9, "R", "15");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 10, "R", "13");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 11, "R", "18");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 12, "R", "22");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 13, "R", "16");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 14, "R", "15");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 15, "R", "13");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 16, "R", "13");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 17, "R", "21");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 18, "R", "19");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 19, "R", "16");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 20, "R", "21");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 21, "R", "14");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 22, "R", "14");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 23, "R", "20");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 24, "R", "13");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 25, "R", "19");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 26, "R", "17");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 27, "R", "20");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 28, "R", "23");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 29, "R", "18");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 30, "R", "16");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 31, "R", "14");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 32, "R", "17");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 33, "R", "15");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 34, "R", "14");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 35, "R", "15");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 36, "R", "14");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 37, "R", "15");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 38, "R", "15");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 39, "R", "15");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 40, "R", "19");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 41, "R", "19");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 42, "R", "18");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 43, "R", "18");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 44, "R", "14");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 45, "R", "13");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 46, "R", "18");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 47, "R", "20");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 48, "R", "17");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 49, "R", "21");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 50, "R", "17");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 51, "R", "15");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 52, "R", "13");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 53, "R", "18");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 54, "R", "17");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 55, "R", "12");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 56, "R", "12");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (1, 57, "R", "14");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 1, "R", "3");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 2, "R", "11");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 3, "R", "7");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 4, "R", "11");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 5, "R", "6");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 6, "R", "6");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 7, "R", "6");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 8, "R", "5");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 9, "R", "2");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 10, "R", "6");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 11, "R", "1");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 12, "R", "2");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 13, "R", "8");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 14, "R", "4");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 15, "R", "5");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 16, "R", "3");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 17, "R", "7");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 18, "R", "3");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 19, "R", "2");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 20, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 21, "R", "4");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 22, "R", "3");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 23, "R", "4");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 24, "R", "1");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 25, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 26, "R", "3");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 27, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 28, "R", "1");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 29, "R", "9");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 30, "R", "-8");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 31, "R", "11");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 32, "R", "12");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 33, "R", "4");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 34, "R", "14");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 35, "R", "7");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 36, "R", "3");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 37, "R", "10");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 38, "R", "-5");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 39, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 40, "R", "3");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 41, "R", "-4");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 42, "R", "2");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 43, "R", "2");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 44, "R", "2");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 45, "R", "5");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 46, "R", "4");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 47, "R", "-1");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 48, "R", "2");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 49, "R", "-5");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 50, "R", "-1");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 51, "R", "1");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 52, "R", "12");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 53, "R", "6");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 54, "R", "12");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 55, "R", "14");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 56, "R", "9");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (3, 57, "R", "14");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 1, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 2, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 3, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 4, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 5, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 6, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 7, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 8, "R", "1");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 9, "R", "16");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 10, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 11, "R", "5");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 12, "R", "8");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 13, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 14, "R", "9");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 15, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 16, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 17, "R", "10");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 18, "R", "26");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 19, "R", "15");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 20, "R", "17");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 21, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 22, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 23, "R", "15");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 24, "R", "9");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 25, "R", "38");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 26, "R", "21");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 27, "R", "15");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 28, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 29, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 30, "R", "13");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 31, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 32, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 33, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 34, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 35, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 36, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 37, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 38, "R", "10");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 39, "R", "9");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 40, "R", "2");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 41, "R", "2");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 42, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 43, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 44, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 45, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 46, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 47, "R", "20");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 48, "R", "21");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 49, "R", "6");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 50, "R", "15");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 51, "R", "9");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 52, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 53, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 54, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 55, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 56, "R", "0");

INSERT INTO propiedad_valor
  (PROPIEDADID, CLAVEID, TIPO, VALOR)
VALUES
  (100, 57, "R", "0");

